//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysWebNHME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulos
    {
        public int IDArticulo { get; set; }
        public Nullable<int> NArticulo { get; set; }
        public string CodigoDeBarras { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IDFamilia { get; set; }
        public Nullable<int> IDLaboratorio { get; set; }
        public Nullable<int> IDUnidadDeMedida { get; set; }
        public Nullable<int> IDAccion { get; set; }
        public Nullable<int> IDGenerico { get; set; }
        public string Concentracion { get; set; }
        public Nullable<double> StockMinimo { get; set; }
        public Nullable<double> StockMaximo { get; set; }
        public Nullable<double> StockRecomendado { get; set; }
        public Nullable<double> PrecioVenta { get; set; }
        public Nullable<double> PrecioVentaMinimo { get; set; }
        public Nullable<bool> EsLote { get; set; }
        public Nullable<double> CostoPromedio { get; set; }
        public Nullable<double> CostoReal { get; set; }
        public Nullable<double> CostoCompra { get; set; }
        public Nullable<double> CostoProyectado { get; set; }
        public string Observacion { get; set; }
        public string CodigoViejo { get; set; }
        public Nullable<bool> EsCodigoInterno { get; set; }
        public Nullable<bool> EsListadoINSS { get; set; }
        public Nullable<int> IDEstanteAsignado { get; set; }
        public Nullable<bool> EsNuevoListadoINSS { get; set; }
        public Nullable<double> PrecioVentaDolar { get; set; }
        public Nullable<int> IDProductoConvertir { get; set; }
        public Nullable<int> IDIndiceConvertir { get; set; }
        public string Presentacion { get; set; }
        public Nullable<bool> EsReuso { get; set; }
        public Nullable<int> IDProductoReuso { get; set; }
        public Nullable<bool> Seleccionar { get; set; }
        public Nullable<int> IDTipoMedicamento { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public Nullable<int> IDUsuarioCrea { get; set; }
        public string HostCrea { get; set; }
        public Nullable<int> IDUsuarioEdita { get; set; }
        public string HostEdita { get; set; }
        public Nullable<int> IDEstadoInventario { get; set; }
    
        public virtual AccionArticulos AccionArticulos { get; set; }
        public virtual EstadoInventario EstadoInventario { get; set; }
        public virtual Familias Familias { get; set; }
        public virtual GenericoArticulos GenericoArticulos { get; set; }
        public virtual Laboratorios Laboratorios { get; set; }
        public virtual UnidadDeMedidas UnidadDeMedidas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
