//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysWebNHME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquiposMac
    {
        public int IDMac { get; set; }
        public string Mac { get; set; }
        public string Usuario { get; set; }
        public string TipoEquipo { get; set; }
        public Nullable<int> IDArea { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual Areas Areas { get; set; }
    }
}
