//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysWebNHME.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBWNHMEEntities : DbContext
    {
        public DBWNHMEEntities()
            : base("name=DBWNHMEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccionArticulos> AccionArticulos { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Articulos> Articulos { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<EquiposMac> EquiposMac { get; set; }
        public virtual DbSet<EstadoInventario> EstadoInventario { get; set; }
        public virtual DbSet<Familias> Familias { get; set; }
        public virtual DbSet<GenericoArticulos> GenericoArticulos { get; set; }
        public virtual DbSet<Laboratorios> Laboratorios { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<TiposDeMov> TiposDeMov { get; set; }
        public virtual DbSet<UnidadDeMedidas> UnidadDeMedidas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<SP_CargarPermisos_Result> SP_CargarPermisos(Nullable<int> inRol)
        {
            var inRolParameter = inRol.HasValue ?
                new ObjectParameter("inRol", inRol) :
                new ObjectParameter("inRol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CargarPermisos_Result>("SP_CargarPermisos", inRolParameter);
        }
    
        public virtual int SP_AdminAreas(Nullable<int> iDArea, Nullable<int> iDDireccion, string descripcion, string desCorta, Nullable<bool> esBodega, Nullable<int> iDUsuarioCrea, string hostCrea, Nullable<int> iDUsuarioEdita, string hostEdita, Nullable<int> iDEstadoInventario, Nullable<int> proceso, ObjectParameter mensaje)
        {
            var iDAreaParameter = iDArea.HasValue ?
                new ObjectParameter("IDArea", iDArea) :
                new ObjectParameter("IDArea", typeof(int));
    
            var iDDireccionParameter = iDDireccion.HasValue ?
                new ObjectParameter("IDDireccion", iDDireccion) :
                new ObjectParameter("IDDireccion", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var desCortaParameter = desCorta != null ?
                new ObjectParameter("DesCorta", desCorta) :
                new ObjectParameter("DesCorta", typeof(string));
    
            var esBodegaParameter = esBodega.HasValue ?
                new ObjectParameter("EsBodega", esBodega) :
                new ObjectParameter("EsBodega", typeof(bool));
    
            var iDUsuarioCreaParameter = iDUsuarioCrea.HasValue ?
                new ObjectParameter("IDUsuarioCrea", iDUsuarioCrea) :
                new ObjectParameter("IDUsuarioCrea", typeof(int));
    
            var hostCreaParameter = hostCrea != null ?
                new ObjectParameter("HostCrea", hostCrea) :
                new ObjectParameter("HostCrea", typeof(string));
    
            var iDUsuarioEditaParameter = iDUsuarioEdita.HasValue ?
                new ObjectParameter("IDUsuarioEdita", iDUsuarioEdita) :
                new ObjectParameter("IDUsuarioEdita", typeof(int));
    
            var hostEditaParameter = hostEdita != null ?
                new ObjectParameter("HostEdita", hostEdita) :
                new ObjectParameter("HostEdita", typeof(string));
    
            var iDEstadoInventarioParameter = iDEstadoInventario.HasValue ?
                new ObjectParameter("IDEstadoInventario", iDEstadoInventario) :
                new ObjectParameter("IDEstadoInventario", typeof(int));
    
            var procesoParameter = proceso.HasValue ?
                new ObjectParameter("Proceso", proceso) :
                new ObjectParameter("Proceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AdminAreas", iDAreaParameter, iDDireccionParameter, descripcionParameter, desCortaParameter, esBodegaParameter, iDUsuarioCreaParameter, hostCreaParameter, iDUsuarioEditaParameter, hostEditaParameter, iDEstadoInventarioParameter, procesoParameter, mensaje);
        }
    
        public virtual int SP_AdminMovimientos(Nullable<int> iDTipoMov, string descripcion, string descCorta, string tipoMov, Nullable<bool> estado, Nullable<int> iDUsuarioCrea, string hostCrea, Nullable<int> iDUsuarioEdita, string hostEdita, Nullable<int> proceso, ObjectParameter mensaje)
        {
            var iDTipoMovParameter = iDTipoMov.HasValue ?
                new ObjectParameter("IDTipoMov", iDTipoMov) :
                new ObjectParameter("IDTipoMov", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var descCortaParameter = descCorta != null ?
                new ObjectParameter("DescCorta", descCorta) :
                new ObjectParameter("DescCorta", typeof(string));
    
            var tipoMovParameter = tipoMov != null ?
                new ObjectParameter("TipoMov", tipoMov) :
                new ObjectParameter("TipoMov", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(bool));
    
            var iDUsuarioCreaParameter = iDUsuarioCrea.HasValue ?
                new ObjectParameter("IDUsuarioCrea", iDUsuarioCrea) :
                new ObjectParameter("IDUsuarioCrea", typeof(int));
    
            var hostCreaParameter = hostCrea != null ?
                new ObjectParameter("HostCrea", hostCrea) :
                new ObjectParameter("HostCrea", typeof(string));
    
            var iDUsuarioEditaParameter = iDUsuarioEdita.HasValue ?
                new ObjectParameter("IDUsuarioEdita", iDUsuarioEdita) :
                new ObjectParameter("IDUsuarioEdita", typeof(int));
    
            var hostEditaParameter = hostEdita != null ?
                new ObjectParameter("HostEdita", hostEdita) :
                new ObjectParameter("HostEdita", typeof(string));
    
            var procesoParameter = proceso.HasValue ?
                new ObjectParameter("Proceso", proceso) :
                new ObjectParameter("Proceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AdminMovimientos", iDTipoMovParameter, descripcionParameter, descCortaParameter, tipoMovParameter, estadoParameter, iDUsuarioCreaParameter, hostCreaParameter, iDUsuarioEditaParameter, hostEditaParameter, procesoParameter, mensaje);
        }
    }
}
