//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysWebNHME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposDeMov
    {
        public int IDTipoMov { get; set; }
        public string Descripcion { get; set; }
        public string DescCorta { get; set; }
        public string TipoMov { get; set; }
        public Nullable<System.DateTime> FechaCrea { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IDUsuarioCrea { get; set; }
        public string HostCrea { get; set; }
        public Nullable<int> IDUsuarioEdita { get; set; }
        public string HostEdita { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
